rootProject.name = "java-cookbook"
include("enum")
include("file")
include("functional-interface")
include("generic")
include("sync")
include("stream")
include("iterable")
include("reflection")
include("collection")
include("native")
