rootProject.name = "java-cookbook"
include("enum")
include("file")
include("lambda")
include("generic")
include("sync")
include("stream")
include("iterable")
include("reflection")
include("collection")
include("native")
include("net")
include("classloader")
include("string-construction")
include("hashmap-type")
